### ISSUE TITLE
Support adding associated domains for ios in config.xml

### ISSUE THREAD

**Issue by sdsanders** [driftyco/ionic-plugin-deeplinks#11] opened 2016-07-12 21:35 UTC
For example, the [cordova-universal-links plugin](https://github.com/nordnet/cordova-universal-links-plugin/blob/master/README.md#cordova-config-preferences) allows you to add a list of hosts within your config.xml to avoid adding those directly in xcode:

```
<universal-links>
    <host name="example.com">
        <path url="*mypath*" />
    </host>
</universal-links>
```

or 

```
<universal-links>
    <host name="example.com" scheme="https" event="ul_myExampleEvent" />
</universal-links>
```

I'd be happy to help add something similar if you're interested in going this direction!

**Comment by mlynch** [comment] 2016-07-21 16:22
Hey @sdsanders, I think it's a nice feature to have. My concern was with a hacky hook to add it manually, but I suppose that could work...

**Comment by mlynch** [comment] 2016-07-21 16:22
Duplicate of #7

**Closed by mlynch** 2016-07-21 16:22 UTC

**Comment by fishgrind** [comment] 2018-09-30 22:07
check here for a quick and easy solution without hooks: https://github.com/ionic-team/ionic-plugin-deeplinks/issues/162
