### ISSUE TITLE
App crashes from JSONObject.wrap when using a device on < API 19

### ISSUE THREAD

**Issue by ngz82** [driftyco/ionic-plugin-deeplinks#65] opened 2016-12-13 15:09 UTC
Android: 4.3 (galaxy s4 i9505)
ionic-plugin-deeplinks: 1.0.12
cordova-plugin-crosswalk-webview 2.1.0
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
Node Version: v6.9.1

IonicDeeplink.java uses the JSONObject.wrap function as part of the deep link functionality and it is causing my app to crash when testing on a device with API level 18 (Android 4.3) , you can see the exception below.
The crash occurs when clicking on a deep link from an email etc.
The .wrap function only exists from API level 19 onwards.

I have worked around it by implementing part of the wrap function from code I found in API 19 and it seems to work fine now but it would be great if the exception could be handled correctly or the wrap implemented properly. The deep link functionality is quite important for many apps and the 4.0->4.3 (API level 15-18) are still almost 15% of the market. 

`12-13 16:46:51.213 3234-3234/co.myapp.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                            java.lang.NoSuchMethodError: org.json.JSONObject.wrap
                                                                at io.ionic.links.IonicDeeplink._bundleToJson(IonicDeeplink.java:139)
                                                                at io.ionic.links.IonicDeeplink.handleIntent(IonicDeeplink.java:68)
                                                                at io.ionic.links.IonicDeeplink.initialize(IonicDeeplink.java:54)
                                                                at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:57)
                                                                at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:172)
                                                                at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:98)
                                                                at org.apache.cordova.PluginManager.init(PluginManager.java:87)
                                                                at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:116)
                                                                at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:144)
                                                                at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:214)
                                                                at co.myapp.app.MainActivity.onCreate(MainActivity.java:32)
                                                                at android.app.Activity.performCreate(Activity.java:5372)
                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2257)
                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349)
                                                                at android.app.ActivityThread.access$700(ActivityThread.java:159)
                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
                                                                at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                at android.os.Looper.loop(Looper.java:137)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5419)
                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:525)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                at dalvik.system.NativeStart.main(Native Method)`

**Comment by mlynch** [comment] 2016-12-13 15:50
Thanks. Duplicate of #59. We're not going to be supporting < 4.4 which is quickly dying out

**Closed by mlynch** 2016-12-13 15:50 UTC

**Comment by emosur** [comment] 2017-06-06 17:10
Hi @ngz82, could you please share the workaround code? We are in the same situation. Thanks in advance.
